version: '3.9'
# Defining the compose version
services:

  # Nginx server
  nginx:
 
    # Build context
    build: ./nginx
    # Mapping machine and container ports
    ports:
      - 80:80

      # Storage volumes
    volumes:
      - static_volume:/staticfiles
      - media_volume:/mediafiles
    depends_on:
      - web
    restart: "on-failure"

  # Django application
  web:
    # Build context
    build: ./web
   
    # Build commands
    command: sh -c "python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn web.wsgi:application --bind 0.0.0.0:8000"
           
    # Storage volumes
    volumes:
      - static_volume:/staticfiles
      - media_volume:/mediafiles
     
    # Exposing port 8000
    expose: 
      - 8000
    depends_on:
      - db
    restart: "on-failure"
  db:
    image: postgres
    env_file:
      - ./web/.env
volumes:
 postgres_data:
 static_volume:
 media_volume: